baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'About'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Vault'
    pageRef = '/vault'
    weight = 20

[taxonomies]
    tag = 'tags'

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
