baseURL = 'https://namjae-kim.namsic.dev/'
languageCode = 'ko-KR'
title = 'Namjae Kim'

[menus]
  [[menus.main]]
    name = 'About'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Vault'
    pageRef = '/vault'
    weight = 20

[taxonomies]
    tag = 'tags'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
