name = 'namsic'
license = 'MIT'
licenselink = 'https://github.com/namsic/namsic.github.io/themes/namsic/LICENSE'
#description = 'Theme description'

# The home page of the theme, where the source can be found
#homepage = 'https://github.com/owner/repo'

# If you have a running demo of the theme
#demosite = 'https://owner.github.io/repo'

# Taxonomy terms
#tags = ['blog', 'company']
#features = ['some', 'awesome', 'features']

#authors = [
#  {name = 'Namjae Kim', homepage = 'namsic.dev'},
#  {name = 'Namjae Kim', homepage = 'namsic.dev'},
#]

[author]
  author = 'Namjae Kim'
  homepage = 'https://namsic.dev'

[original]
  author = 'Namjae Kim'
  homepage = 'https://namsic.dev'
  repo = 'https://github.com/namsic/namsic.github.io'
